#!/usr/bin/env node
// Generated entry points contain links, never copies of role/command procedures.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
function outputs() {
  const files = new Map();
  const manifest = JSON.parse(fs.readFileSync(path.join(root, '.claude-plugin/plugin.json'), 'utf8'));
  files.set('.codex-plugin/plugin.json', JSON.stringify({ ...manifest,
    description: 'Shared Crew roles, crafts and project standards for Claude Code and Codex.',
    skills: './skills/',
    interface: { displayName: 'Crew', shortDescription: 'Specialized roles and shared engineering standards',
      longDescription: 'One role catalog, shared crafts and crew.json, with host-specific entry points and guarded file edits.',
      developerName: manifest.author.name, category: 'Productivity',
      capabilities: ['Read', 'Write'], websiteURL: manifest.homepage,
      defaultPrompt: ['Use Crew to review this project.'] },
  }, null, 2) + '\n');
  const roles = fs.readdirSync(path.join(root, 'agents')).map(f => f.replace(/\.md$/, ''));
  for (const file of fs.readdirSync(path.join(root, 'commands')).filter(f => f.endsWith('.md')).sort()) {
    const alias = file.slice(0, -3);
    const command = fs.readFileSync(path.join(root, 'commands', file), 'utf8');
    const description = command.match(/^description: (.+)$/m)?.[1].replace(/^"|"$/g, '');
    if (!description) throw new Error(`Missing description: ${file}`);
    const matched = roles.filter(role => new RegExp(`(?<![a-z-])${role}(?![a-z-])`).test(command));
    const links = matched.map(role => `- [${role}](../../agents/${role}.md)`).join('\n');
    files.set(`skills/${alias}/SKILL.md`,
      `---\nname: ${alias}\ndescription: ${JSON.stringify(description)}\n---\n\n` +
      `<!-- Generated by scripts/sync-codex.js; edit canonical commands/agents instead. -->\n\n` +
      `In Codex, first read and follow the [Codex adapter](../../integrations/codex/README.md).\n` +
      `In Claude Code, use the command's native subagent and argument conventions.\n` +
      `Then read the canonical [${alias} procedure](../../commands/${file}) for the user's task.\n\n` +
      (links ? `Read these role definitions before acting:\n\n${links}\n` : 'This procedure runs without a specialist role.\n'));
  }
  return files;
}
function sync(check = false) {
  const files = outputs();
  const skillRoot = path.join(root, 'skills');
  if (fs.existsSync(skillRoot)) for (const name of fs.readdirSync(skillRoot)) {
    const entry = path.join(skillRoot, name, 'SKILL.md');
    if (fs.existsSync(entry) && fs.readFileSync(entry, 'utf8').includes('Generated by scripts/sync-codex.js') &&
        !files.has(`skills/${name}/SKILL.md`)) {
      throw new Error(`Retired generated skill still present: ${name}; remove it explicitly`);
    }
  }
  for (const [relative, content] of files) {
    const target = path.join(root, relative);
    if (check) {
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) throw new Error(`Out of date: ${relative}`);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, content);
    }
  }
  return files;
}
if (require.main === module) { sync(process.argv.includes('--check')); console.log('Codex entry points are synchronized.'); }
module.exports = { outputs, sync };
